<link rel="stylesheet" href="<?= r(); ?>css/zui.uploader.min.css">
<script src="<?= r(); ?>js/zui.uploader.min.js"></script>
<div class="row">
    <form class="form-horizontal" id="add-form" action="/auth/team/add" method="POST">
        <div class="form-group">

        </div>
        <div class="form-group">
            <label for="field-remark" class="col-sm-2">视频上传</label>
            <div class="col-sm-8">
                <div id="uploader" class="uploader">
                    <div class="file-list" data-drag-placeholder="请拖拽文件到此处"></div>
                    <button type="button" class="btn btn-primary uploader-btn-browse"><i
                                class="icon icon-cloud-upload"></i> 选择文件
                    </button>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="field-remark" class="col-sm-2">备注</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="field-remark" name="remark"
                       value=""/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" name="submit" value="1" class="btn btn-info">上传</button>
            </div>
        </div>
    </form>
</div>
<script>
    $(function () {
        $("#add-form").myAjaxForm();
        $('#uploader').uploader({
            autoUpload: true,            // 当选择文件后立即自动进行上传操作
            url: '/admin/video/add',  // 文件上传提交地址
            filters: {
                // 只允许上传图片或图标（.ico）
                mime_types: [
                    {title: '视频', extensions: 'mp4'},
                ],
                // 不允许上传重复文件
                prevent_duplicates: true
            }
        });
    })
</script>